logged_in/routes.py
from flask import redirect, make_response, jsonify, abort, request, flash, session, url_for, Blueprint, redirect, render_template
from werkzeug.utils import secure_filename
from database.models import db, User
from datetime import datetime
from logged_in.hash_cracker import hash_types, hasher
from time import perf_counter, strftime, gmtime
from os import remove, path
from mimetypes import guess_extension
from logged_in.archive_cracker import file_handler
from multiprocessing import TimeoutError
from multiprocessing.pool import ThreadPool
import logging
from sqlalchemy.exc import IntegrityError
from .wrapper import require_api_token
from logged_in.hash_encoder import encoder
import threading
from mail.mail_helper import send_arch_message
import copy
from base64 import b64encode
from werkzeug.exceptions import RequestEntityTooLarge
from humanfriendly import format_timespan

logged_in_bp = Blueprint('logged_in_bp', __name__, template_folder='templates', static_folder='static')


@logged_in_bp.route('/index', methods=['GET'])
@require_api_token
def index():
    return "Hello, World!"

@logged_in_bp.route('/', methods=["GET"])
@logged_in_bp.route('/home', methods=["GET"])
@require_api_token
def home_page():
    return render_template("solve.htm", username=session['username'])

@logged_in_bp.route('/logout', methods=['POST'])
@require_api_token
def log_out():
    logging.info('[LOGOUT] Got logout request')
    session.pop('ACCESS_TOKEN', None)
    session.pop('username', None)
    session.pop("DO_NOT_REMEMBER", None)
    return redirect(url_for('logged_out_bp.main_page'))

@logged_in_bp.route('/settings', methods=['POST', 'GET'])
@require_api_token
def settings():
    logging.info('[SETTINGS] Got settings request')
    if request.method == 'GET':
        return render_template("solve.htm", settings=1)
    else:
        form = request.form
        if form.get('remember_hashes'):
            session["DO_NOT_REMEMBER"] = True
            flash("Hashes won't be remembered during this session", category='message')
        return render_template("solve.htm", settings=1)

@logged_in_bp.route('/deleteUser', methods=['DELETE', 'GET'])
@require_api_token
def delete_user():
    logging.info('[DELETE] Got delete user request')
    user = User.query.filter_by(username=session['username']).first()
    if user is None:
        abort(400, "USER DOES NOT EXIST") #TODO
    else:
        db.session.delete(user)
        db.session.commit()
        session.pop('ACCESS_TOKEN', None)
        session.pop('username', None)
        flash('User deleted', category='message')
        return redirect(url_for('logged_out_bp.main_page'))

@logged_in_bp.route('/arch', methods=['GET'])
@require_api_token
def arch():
    return render_template('solve.htm', arch=1)
    
@logged_in_bp.route('/hash/encode', methods=['POST', 'GET'])
@require_api_token
def hash_encoder():
    if request.method == 'GET':
        return render_template('solve.htm', hash_encode=1)
    else:
        logging.info('[HASH] Got hash encode request')
        text_to_hash = request.form.get('text_to_encode')
        mode = request.form.get('mode')
        if text_to_hash == "":
            flash('No text provied', 'error')
            return render_template('solve.htm', hash_encode=1)
        start_time = perf_counter()
        hashed = encoder.encode(text=text_to_hash, mode=mode)
        elapsed_time = perf_counter() - start_time  
        data = {
            "Original": text_to_hash,
            "Encoded": hashed,
            "Type": mode,
            "Encoding duration": format_timespan(elapsed_time),
        }
        return render_template('solve.htm', hash_encode=1, data=data)

@logged_in_bp.route('/hash/decode', methods=['POST', 'GET'])
@require_api_token
def hash_decoder():
    if request.method == 'GET':
        return render_template('solve.htm', hash_decode=1)
    else:
        logging.info('[HASH] Got hash decode request')
        hash_to_crack = request.form.get('hash_encoded')
        if hash_to_crack is None:
            return render_template("solve.htm", hash_decode=1, error=NO_HASH_MESSAGE)
        else:
            hash_type = hash_types.get_hash_type(hash_to_crack)
            if hash_type:
                start_date = datetime.now()
                start_time = perf_counter()
                dehashed = hasher.single(hash_to_crack, hash_type)
                # this part is needed if polish signs appear - they turn dehashed value to HEX in form $HEX[\w]
                import re
                logging.info(re.match(r"(?<=HEX)\w+", dehashed))
                if re.search(r'(\$HEX\[\w+\])', dehashed):
                    import codecs
                    dehashed = codecs.decode(str.encode(re.split(r"(\w+)", dehashed)[3]), "hex_codec").decode('utf-8') 
                elapsed_time = perf_counter() - start_time
                end_date = datetime.now()
                if dehashed:
                    data = {
                        'Type': hash_types.get_hash_type(hash_to_crack),
                        'Original': hash_to_crack,
                        'Decoded': dehashed,
                        'Dehashing duration': format_timespan(elapsed_time),
                        'Dehash started at': str(start_date.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]),
                        'Dehash ended at': str(end_date.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3])
                    }
                    return render_template('solve.htm', hash_decode=1, data=data)
                else:
                    flash(CANNOT_DECRYPT_MESSAGE)
                    return render_template('solve.htm', hash_decode=1) 
            else:
                flash(NOT_CORRECT_HASH_MESSAGE)
                return render_template('solve.htm', hash_decode=1) 


@logged_in_bp.route('/arch/decode', methods=['POST', 'GET'])
@require_api_token
def archive_decode():
    if request.method == 'GET':
        return render_template("solve.htm", arch=1 )
    else:
        logging.info('[ARCH] Got archive decrypt request')
        try:
            if not 'file' in request.files:
                return render_template("solve.htm", arch=1, error=NO_FILE_ERROR_MESSAGE) 
            else:
                arch_file = request.files.get('file')
                arch_temp_file = request.files.get('file')
                arch_file_name = secure_filename(arch_file.filename)
                arch_file_path = path.join(TEMP_PATH, str(int(datetime.now().timestamp())))
                arch_file.save(arch_file_path)
                arch_file_mime_type = file_handler.get_file_mime_type(arch_file_path)
                if arch_file_mime_type not in file_handler.get_allowed_mime_types():
                    flash(f'Wrong file type provided: {guess_extension(arch_file_mime_type, strict=False)}', 'error')
                    return render_template("solve.htm", arch=1)
                else:
                    
                    user = User.query.filter_by(username=session['username']).first()
                    thread = threading.Thread(target=decrack, args=(arch_file_path, arch_file_mime_type, arch_file_name, user.username, user.email))
                    thread.daemon = True                    
                    thread.start()
                    message = f"""
                    We will try to decrypt archive in next: {format_timespan(DECRACK_TIMEOUT)}.
                    Answer will be sent to your email.
                    """
                    flash(message, 'message')
                    return render_template("solve.htm", arch=1 )
        except RequestEntityTooLarge as e:
            message = 'File too large'
            flash(message, 'error')
            logging.info("[ARCH] " + e.description)
            return render_template("solve.htm", arch=1)
           

def decrack(arch_file_path, arch_file_mime_type, arch_file_name, username, email):
    
    start_date = datetime.now()
    start_time = perf_counter()
    pool = ThreadPool(processes=1)
    pool_result = pool.apply_async(file_handler.handle_file, (arch_file_path, arch_file_mime_type))
    try:
        password = pool_result.get(timeout=DECRACK_TIMEOUT)
    except TimeoutError as e:
        pool.terminate()
        logging.info(f'[ARCH] Archive cannot be decrypted after given time of {format_timespan(DECRACK_TIMEOUT)}')
        send_arch_message(user=username, mail=email, file_name=arch_file_name,time=DECRACK_TIMEOUT)
        return
    elapsed_time = perf_counter() - start_time
    end_date = datetime.now()
    pool.terminate()   
    duration_message = f"""
    <div>Cracking password started at: {start_date}</div>
    <div>Cracking password ended at: {end_date}</div>
    """
    file_handler.clear_file(arch_file_path)
    send_arch_message(user=username, mail=email, password=password, file_name=arch_file_name, time=elapsed_time, additional_info=duration_message)

@logged_in_bp.errorhandler(404)
def not_found(error):
    logging.info(f'[ERROR] {error}')
    return make_response(jsonify(
        {
            'error': 'Not found',
            'timestamp': datetime.now()
        }
    ), 404)


@logged_in_bp.errorhandler(500)
def not_found(error):
    logging.info(f'[ERROR] {error}')
    return make_response(jsonify(
        {
            'error': 'Server error',
            'timestamp': datetime.now()
        }
    ), 500)


@logged_in_bp.errorhandler(413)
def request_entity_too_large(error):
    message = 'File too large'
    flash(message, 'error')
    logging.info("[ARCH] File too large")
    return render_template("solve.htm", arch=1)


@logged_in_bp.errorhandler(400)
def not_handled(error):
    logging.info(f'[ERROR] {error}')
    if error:
        return make_response(jsonify(
            {
                'error': error.description,
                'timestamp': datetime.now()
            }
        ), 400)
    else:
        return make_response(jsonify(
            {
                'error': 'Cannot proceed this request',

logged_in/templates/home.html
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CryptHelper</title>
  <link rel="stylesheet" href="{{ url_for('logged_in_bp.static', filename='css/home.css') }}">
  <link rel="stylesheet" href="{{ url_for('logged_in_bp.static', filename='css/archive.css') }}">
  <link rel="stylesheet" href="{{ url_for('logged_in_bp.static', filename='css/hash.css') }}">
</head>
<body>
<nav id="slide-menu">
	<ul>
		<li class="home" onclick='mainPage()'>Home</li>
		<li class="hashdecode" onclick='hashDecode()'>Hash decode</li>
		<li class="hashencode" onclick='hashEncode()'>Hash encode</li>
		<li class="archcrack" onclick='archCrack()'>Archive decrypt</li>
		<li class="sep settings" onclick='settings()'>Settings</li>
		<li class="logout" onclick='logOut()'>Logout</li>
	</ul>
</nav>
<div id="content">
	<div class="menu-trigger"></div>
	<div class='solve_block'>{% block solve %}{% endblock %}</div>
</div>
  <script  src="{{ url_for('logged_in_bp.static', filename='js/home.js') }}"></script>
  <script  src="{{ url_for('logged_in_bp.static', filename='js/functions.js') }}"></script>
  <script  src="{{ url_for('logged_in_bp.static', filename='js/upload.js') }}"></script>
</body>
</html>

logged_in/templates/solve.htm
{% extends "home.html" %} {% block solve %} {%- if arch %}
<h1 align="center">Archive cracker</h1>
<br>
<h3 align="center">On this subpage you can crack password-encrypted archives.</h3>
<div align="center">Select a local file and send it by clicking <b><i>Submit</i></b></div>
<br>
<div class='messages'>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
    <h3 class="{{category}}">{{ message }}</h3>
    {% endfor %} {% endif %} {% endwith %}
</div>
<form class='file_form' action="{{ url_for('logged_in_bp.archive_decode')}}" method="post" enctype="multipart/form-data">

    <div class="input-file-container">
        <input class="input-file" id="file" name='file' type="file" oninput="Filevalidation(this)">
        <label tabindex="0" for="file" class="input-file-trigger">Select a file...</label>
    </div>
    <p class="file-return"></p><br>

    <input type="submit" id='submit' value="submit" class='form_input_submit'>
    <label tabindex="0" for="submit" class="input-file-submit-trigger">Submit</label>

    <br>

</form> <br> {% elif hash_decode %}
<h1 align="center">Hash decoder</h1>
<br>
<h3 align="center">On this subpage you can decode hashes.</h3>
<div align="center">Enter encoded text and send it by pressing <b><i>Submit</i></b></div>
<br>
<form action="{{ url_for('logged_in_bp.hash_decoder')}}" method="post">
    <br>
    <label for="inp" class="inp">
                    <input name="hash_encoded" type="text" id="inp" placeholder="&nbsp;">
                    <span class="label">Hash to decode</span>
                    <span class="border"></span>
                </label>
    <br>
    <input type="submit" id='submit' value="submit" class='form_input_submit'>
    <label tabindex="0" for="submit" class="input-file-submit-trigger">Submit</label>
</form> <br>
<div class='messages'>
    {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %} {% endif %} {% endwith %}
</div>
<div id='solve_hash_inner'>
    <div>
        {%- if data is defined %}
        <table class='hash_decoded_table' style="width:100%">
            <th></th>
            {% for key, value in data.items() %} {% if loop.index0 % 2 == 0 %}
            <tr class='even'>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
            {% else %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endif %} {% endfor %}
        </table>
        {%- elif error is defined %}
        <div>
            {{error}}
        </div>
        {% else %}
        <div>
        </div>
        {% endif %}
    </div><br>
</div>
{% elif hash_encode %}
<h1 align="center">Hash encoder</h1>
<br>
<h3 align="center">On this subpage you can get hash of given text.</h3>
<div align="center">Enter text, choose hash type and encode it by pressing <b><i>Submit</i></b></div>
<br>
<form action="{{ url_for('logged_in_bp.hash_encoder')}}" method="post">
    <label for="inp" class="inp">
                    <input type="text" id="inp" name="text_to_encode" placeholder="&nbsp;">
                    <span class="label">Text to encode</span>
                    <span class="border"></span>
                </label>
    <br>
    <div class="custom-select">
        <select name='mode'>
                        <option value="md5">md5</option>
                        <option value="sha1">sha1</option>
                        <option value="sha256">sha256</option>
                        <option value="sha384">sha384</option>
                        <option value="sha512">sha512</option>
                    </select>
    </div>

    <br>
    <input type="submit" id='submit' value="submit" class='form_input_submit'>
    <label tabindex="0" for="submit" class="input-file-submit-trigger">Submit</label>
</form> <br>
<div class='messages'>
    {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %} {% endif %} {% endwith %}
</div>
<div id='encode_hash_inner'>
    {%- if data is defined %}
    <table class='hash_encoded_table'>
        <th></th>
        {% for key, value in data.items() %} {% if loop.index0 % 2 == 0 %}
        <tr class='even'>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% else %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endif %} {% endfor %}
    </table>
    {%- elif error is defined %}
    <div>
        {{error}}
    </div>
    {% else %}
    <div>
    </div>
    {% endif %}
</div><br> {% elif settings %}
<h1 align="center">Settings</h1>
<form action="{{ url_for('logged_in_bp.settings')}}" method='POST'>
    <input type="checkbox" name="remember_hashes" id="remember_hashes">
    <label for="remember_hashes">Do not remember my encoded hashes during this session </label>

    <button type="submit">Save</button>

</form>

<button name="deleteButton" onclick="checkUser()">Delete user</button>
<br> {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
<div class='messages'></div>
{% for category, message in messages %}
<h3 class="{{category}}">{{ message }}</h3>
{% endfor %}
</div>
{% endif %} {% endwith %} {% else %}
<div class="main_page">
    <h1 align="center">Welcome {{username}} to CryptoHelper</h1>
    <br>
    <h3 align="center">On this website you can try to decode hash, encode hash and break the password of couple of archive types listed below.</h3>
    <div align="center">Choose your option from the menu on the left</div>
    <br>
    <div>
        <table style="width:100%">
            <tr>
                <th>Available hashes</th>
                <th>Available archive types</th>
            </tr>
            <tr>
                <td align="center">md5</td>
                <td align="center">.zip</td>
            </tr>
            <tr>
                <td align="center">sha1</td>
                <td align="center">.rar (slow)</td>
            </tr>
            <tr>
                <td align="center">sha256</td>
                <td align="center">.7z (slow)</td>
            </tr>
            <tr>
                <td align="center">sha384</td>
            </tr>
            <tr>
                <td align="center">sha512</td>
            </tr>
        </table>
    </div>
</div>

{% endif %} {% endblock %}